name: Compile EntryClient

on:
  pull_request:
    branches:
      - master

env:
  ENTRYCLIENT_VERSION: "2.0"

jobs:
  setup:
    name: Compile EntryClient
    runs-on: ubuntu-latest
    container:
      image: epidata/fpcbuild:3.2.2

    strategy:
      fail-fast: false
      matrix:
        profile: [linux64, win64, darwin64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Maven settings.xml
        uses: whelk-io/maven-settings-xml-action@v22
        with:
          output_file: "/etc/maven/settings.xml"
          servers:
            '[{
            "id": "github",
            "username": "${{ secrets.CI_USER }}",
            "password": "${{ secrets.CI_PASSWORD }}"
            }]'
          repositories:
            '[
              {
                "id": "central",
                "url": "https://repo1.maven.org/maven2"
              },
              {
                "id": "github",
                "url": "https://maven.pkg.github.com/epidata-dk/parent/",
                "snapshots": {
                  "enabled": "true"
                }                
              }
            ]'

      - name: Compile ${{ matrix.profile }}
        run:  mvn compile -P${{ matrix.profile }}